#!/bin/bash

/media/castello/Linus/labs/riscv/freedom-e-sdk/work/build/openocd/bin/openocd \
	-f /media/castello/Linus/labs/riscv/Espruino/targetlibs/fe300/env/freedom-e300-hifive1/openocd.cfg & \
	/media/castello/Linus/labs/riscv/freedom-e-sdk/work/build/riscv-gnu-toolchain/bin/riscv64-unknown-elf-gdb /media/castello/Linus/labs/riscv/Espruino/$1 \
	--batch \
	-ex "set remotetimeout 240" \
	-ex "target extended-remote localhost:3333" \
	-ex "monitor reset halt" \
	-ex "monitor flash protect 0 64 last off" \
	-ex "load" \
	-ex "monitor resume" \
	-ex "monitor shutdown" \
	-ex "quit"
	